apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -peer-pods-s390x

resources:
- ../peer-pods

images:
- name: quay.io/confidential-containers/runtime-payload
  newName: quay.io/confidential-containers/runtime-payload
  newTag: kata-containers-6abfb9deadc03154f91896e78ea024e55928c9f4-s390x
