name: ccruntime e2e tests
on:
  workflow_call:
    inputs:
      target-branch:
        required: false
        type: string
        default: ""
      commit-hash:
        required: true
        type: string

permissions:
  contents: read

jobs:
  e2e:
    name: operator tests
    strategy:
      fail-fast: false
      matrix:
        runtimeclass:
          - "kata-qemu"
          - "kata-clh"
        instance:
          - "az-ubuntu-2004"
          - "az-ubuntu-2204"
          - "s390x"
        ccruntime_overlay:
          - ''
          - "peer-pods"
        exclude:
          - runtimeclass: "kata-clh"
            instance: "s390x"
    runs-on: ${{ matrix.instance }}
    steps:
      - name: Take a pre-action for self-hosted runner
        run: |
          if [ -f ${HOME}/script/pre_action.sh ]; then
            ${HOME}/script/pre_action.sh cc-operator
          fi

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0

      - name: Rebase atop of the latest target branch
        run: |
          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
        env:
          TARGET_BRANCH: ${{ inputs.target-branch }}

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible python-is-python3

      - name: Run e2e tests
        timeout-minutes: 45
        run: |
          cd tests/e2e
          export PATH="$PATH:/usr/local/bin"
          args="-u"
          if [ $RUNNING_INSTANCE = "s390x" ]; then
            args=""
          fi
          ./run-local.sh -t -r "${{ matrix.runtimeclass }}" -o "${{ matrix.ccruntime_overlay }}" "${args}"
        env:
          RUNNING_INSTANCE: ${{ matrix.instance }}

      - name: Take a post-action
        if: always()
        run: |
          if [ -f ${HOME}/script/post_action.sh ]; then
            ${HOME}/script/post_action.sh cc-operator
          fi
